// <auto-generated />
namespace EvidentTestDashboard.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_label_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_label_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201512161415314_added_label_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
